[project]
name = "data-engineering-projects"
version = "0.1.0"
description = "A series of hands-on project to learn Data Engineering concepts and tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pandera>=0.27.1",
    "sqlalchemy>=2.0.45",
]
